vehicle:
  properties:
    gearTypes:
      automatic: 31232
      duplex: 56765
      manual: 213213
      semi-automatic: 87978
    bodyTypes:
      bus: 3424
      convertible: 34
      coupe: 7567
    fuelTypes:
      diesel: 5345
      electric: 213
      petrol: 6765
    wheelPlacement:
      front-left: fwl
      front-right: fwr
      rear-left: bwl
      rear-right: bwr
    rimTypes:
      original: 3123
      supplier: 657
    tyreTypes:
      all-season: 564
      summer: 432
      winter: 85677
    colors:
      beige: 323
      black: 8797
      blue: 23423
      brown: 546
      bronze: 35
      gold: 234
      green: 675
      gray: 24e2
    upholestryTypes:
      cloth: 213
      leather: 978

orika:
  enabled: true
  useBuiltinConverters: true
  useAutoMapping: true
  mapNulls: true
  dumpStateOnException: true
  favorExtension: true
  captureFieldContext: true
